pipeline {
    agent any
    environment {
                GLOBE ='testing'
                UNIVERSE ='loading'
                secret =credentials('03894736-20fe-49f3-ace6-27401287be90')
                user =credentials('7581673d-169f-436c-a9bb-e12f253e61fd')
            }
    stages {
        stage('Predifined variables') {
            steps {
                sh 'env | sort'
                echo "$LOGNAME"
                echo "$USER"
                echo "$secret"
                echo "$secret"
            }
        }
        stage('Global variable') {
            steps {
                echo "$GLOBE"
                echo "$UNIVERSE"
            }
        }
        stage('Stage defined variable') {
            environment {
                STEP ='process'
                STEPS ='PROCESSing'
            }
            steps {
                echo "$GLOBE"
                echo "$STEPS"
                echo "$BETTER"
                echo "$user"
            }
        }    
    }
}
